### ISSUE TITLE
Issues with v8

### ISSUE THREAD

**Issue by Amestrim** [xtjoeytx/GServer-v2#43]
compiler errors with NewFromUtf8Literal and ToLocalChecked
error C2039: 'NewFromUtf8Literal': is not a member of 'v8::String'
'ToLocalChecked': is not a member of 'v8::Local<v8::String>'
im new to c++ and followed the build guide

**Comment by Amestrim** [comment]
I am compiling for winodws 10 x64

**Comment by 2ndwolf** [comment]
That error is due to not using the right v8 version. As of now this repo is using version `9.1.269.9`. Be sure to also find and replace the old version to this one in the CMakeLists.txt files.

Also you will get a runtime error mentionning pointer compression, append this line:
`target_compile_definitions(${PROJECT_NAME} PUBLIC NDEBUG V8_COMPRESS_POINTERS V8_31BIT_SMIS_ON_64BIT_ARCH)`
to the root CMakeLists.txt to fix that.
